name: quick_blue
description: A cross-platform BluetoothLE plugin for Flutter.
version: 0.6.0
homepage: https://github.com/woodemi/quick_blue
repository: https://github.com/woodemi/quick_blue/tree/master/quick_blue

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  #  quick_blue_platform_interface: ^0.4.0-dev.0
  quick_blue_macos: ^0.4.0-dev.0
  quick_blue_windows: ^0.4.0-dev.0
  #  quick_blue_linux: ^0.2.0-dev.0
  convert: ^3.0.0
  plugin_platform_interface: ^2.0.0
  logging: ^1.0.2
  quick_blue_platform_interface: ^0.4.0-dev.0
  bluez: ^0.7.9
  collection: ^1.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.quick_blue
        pluginClass: QuickBluePlugin
      ios:
        pluginClass: QuickBluePlugin
      macos:
        default_package: quick_blue_macos
      windows:
        default_package: quick_blue_windows
      linux:
        default_package: quick_blue_linux