name: quick_blue
description: A cross-platform BluetoothLE plugin for Flutter.
version: 0.6.0
homepage: https://github.com/woodemi/quick_blue
repository: https://github.com/woodemi/quick_blue/tree/master/quick_blue

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  plugin_platform_interface: ^2.1.3
  logging: ^1.1.1
  bluez: ^0.8.1
  collection: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter